### PR TITLE
S8R/S6R setup script 

### PR DESCRIPTION
**Pull request by offer-shmuely**
S8R/S6R setup tool

- choose the correct version for the accst receivers
- update script presentation name 
- enter the images (bmp&img) into the script folder
- rename (for the better) the names of the fields
- reorder the fields to be more consistent
- add simulator mode for debugging

  
Note:
I know that on regular basis we prefer to keep other company script outside with links, so the original developer of the script will not be bind to edgeTx version, but in FrSky case I feel it is not the same
1. the script have openTX license
2. FrSky have couple of script and it hard for the user to choose the correct one
3. the fields have very bad name, that make the use of the gyro intimidating 
4. FrSky did not develop the script for the accst receivers from 2020-07-06, and it does not like they are going to give a better service to it's client on this area

### CODE REVIEW

**Comment by offer-shmuely** [comment]
old

image


new
image


image


image

**Comment by pfeerick** [comment]
I have no issue with this being added, particularly when it's basically abandon-ware, and someone is willing to support/improve it. It doesn't hurt that I have an SxR or two :laughing:

**Comment by offer-shmuely** [comment]
abandon-ware? Ha ha
You learn new things every day😀
Can you take a look that text is clear?

**Comment by offer-shmuely** [comment]
adding @JimB40
is that look better?

image
image

**Comment by JimB40** [comment]
Yep it is. My second name is "Whitespace" ;)
To be all good looking move S8R/S6R in header same amount px as content, making progres bar narrower.

**Comment by offer-shmuely** [comment]
like this?

image

**Comment by pfeerick** [comment]
This looks and seems to be working great. I'm ok with merging this as is, but thought I'd ask beforehand:

I finally realised why sometimes why it didn't before when you press enter... you need to wait for the values to update onscreen before it will let you continue. Something worth mentioning onscreen somehow?

**Comment by offer-shmuely** [comment]
Do you mean in setup, or calibrate?

**Comment by pfeerick** [comment]
For calibrate... you need to wait for the values to update before it lets you move to the next step... which always confused me with the original version as seemed to be unresponsive when you pressed enter at some times, and responsive at others.

**Comment by offer-shmuely** [comment]
Ya, i had this issues in the past as well,
Took a long time to understand the logic 
I will take the challenge and I will search a way to give visual indication

**Comment by pfeerick** [comment]
The simplest option would just be a prompt (i.e. "Wait for the values to update before moving to next step" or words to that effect). 

Or maybe some way of storing the values from step to step, and then they can change color as they update... i.e. when you press enter, they get reset to red, and then as the new values come in, they would sequentially turn green (since they seem to update in sequence)... just an idea?

**Comment by offer-shmuely** [comment]
added colorful indication (thanks to peter on the suggestion)

image

**Comment by offer-shmuely** [comment]
now with:
* indication bars in correct side 
* shades


image

**Comment by pfeerick** [comment]
LGTM... thank you for those final hopefully beneficial to others quality of life touches! :)

**Comment by Jim7695** [comment]
HI Guys - I like the look of this new script.  Really nice work.  I have a problem maybe you can assist with.  I recently installed a FRSKY RB30+ redundant bus module in a new plane.  While trying to execute the Parameter Set Script, using my RadioMaster TX16S, the script opened, but no data was received.  Currently using Edge TX 2.9.1.  I rolled my firmware back to 2.8.5 and the script worked.  Any thoughts.  Thanks. Jim

**Comment by 3djc** [comment]
And what is the point exactly of mentioning that here when you have opened an issue ?

**Comment by Jim7695** [comment]
My apologies if I have bothered or offended you in any way.  I am new to the edge tx environment, ran across this post and thought I could ask a question.  


Jim (Torch) Anderson

**Comment by pfeerick** [comment]
This really isn't the place to ask that question, since it's not related to the SxR script plus this PR is closed. Best to wait to see if anyone can respond in EdgeTX/edgetx#4297 You're somewhat lucky the scripts even work, since they are probably not tested by Frsky to work with EdgeTX at all. 

Can you link in that issue to where you got the scripts from, and double check if they are the latest version - as depending on where you go on the frsky site, you may not actually have the latest version. Going from [this older OpenTX issue](https://forum.alofthobbies.com/index.php?threads/rb30-unable-to-change-setting-thru-lua-script-no-enter-or-backwards-function.1825/), it seems they were somewhat flakely even on OpenTX.

**Comment by Jim7695** [comment]
Thanks Peter.  I believe I have tje most recent script but will check that
as well.

Any advice is appreciated.

Cheers.  Jim

**Pull request merged**
