### PR TITLE
flight history UI update

### PR DESCRIPTION
**Pull request by offer-shmuely**
FlightsHistory version 1.1
reverse order of flight (last flight on top)
indentation of flight number (since do not have yet gui control to present tables)

### CODE REVIEW

**Comment by pfeerick** [comment]
> indentation of flight number (since do not have yet gui control to present tables)

Needs #111 or is that something else?

**Comment by offer-shmuely** [comment]
Something else.
The libGui that this tool use, is build inside, does not use an external one.
Anyhow, to align the two fields, I need that the libGui will be enhanced to present tables (not managed to do it yet)
Or to print them with fixed-spacing font, but from some unclear reason, the edgeTx was built around proportional fonts😥😥
So for now i put the number of flight first, with padding to 000

**Comment by pfeerick** [comment]
Looks like you might have missed adding `main.lua`? This ran without startup error when I added https://github.com/offer-shmuely/edgetx-x10-scripts/blob/main/SCRIPTS/TOOLS/FlightsHistory/main.lua if that is the right file to add.

**Comment by offer-shmuely** [comment]
yes, I missed it, too  many branches to commit to
sorry.
added.

**Pull request merged**
