### PR TITLE
value2 add min max

### PR DESCRIPTION
**Pull request by offer-shmuely**
value2: add mix/max presentation upon end of flight (as part of post-flight-statistics)

### CODE REVIEW

**Comment by phileville** [comment]
Nice work! I am adding this widget to the User Guide  - what does configuration option "Post Fix" do - it looks like it appends a text label after the configured telemetry name label.  Is it for anything else?

**Comment by offer-shmuely** [comment]
When you have many telemetry 
You can label them with more informative text

Tmp1, tmp2 --> 
"Tmp1 esc"
"Tmp2 motor"

Bat1 --> bat1 left
Bat2 --> bat2 right

**Comment by phileville** [comment]
Ok, I see - why did you call it Postfix in the configuration options?  Why not simply call it Label or TextLabel?

**Comment by pfeerick** [comment]
Or "Suffix", if it's appended to the end ;)

**Comment by offer-shmuely** [comment]
correct, Suffix will be better.
fixed

**Pull request merged**
