### PR TITLE
SoarETX V2 improvements and support for F3J/F5J 4-servo wing templates

### PR DESCRIPTION
**Pull request by frankiearzu**
After talking with the original Author.. he was OK with me doing the enhancements.  Looks like he moved to Jeti Radio and will not spend much time enhancing the ETX version.

The V1 and V2 code are stored in different sub-directories, and the appropriate code will be run depending on the version used in the parameter of the main.lua for the widget.  Both can co-exist. V1 totally backward compatible, and besides just updating the LUA Widgets, it will work with existing models already setup in the radio without changes.

List of changes:
1.  Fix GetCurve logic to detect if it is affected by the bug in some ETX versions, and correct if needed.  this is for backward compatibility
2. V1 code is completely backward compatible to current models in the radio. 
3. V1: The 480x320 was a bit behind in fixes compared to 480x272.. Really there is no difference, so updated the files.
4. V2: Reorganize the code so that we don't have a proliferation of files.  For example, in V1 there was separate LUA for the Mixers for each type of Glider, in V2 instead, a glider type parameter is passed, and the single mixer LUA initialize the proper content of the menu depending of the glider type.  Same for switches.  For wings, there was 2 different ways to let the model that it was in configuration mode (also dependent of the model template)
5.  V2: Added F3J and F5J templates and configuration. The templates came from SoarOTX and are compatible.
6.  V2: Added SOUNDS who are specific for gliders. (EXTERNAL in the sounds/phrases project)
7. V2: The Scoring workflow for F3J/F5J are in the initial state.. the workflow do the proper steps, but the scoring is still not saved to a file.. But the plane/glider works well.

NEXT STEPS: work more on the scoring code.

image
image
image
image
image
image

### CODE REVIEW

**Comment by pfeerick** [comment]
Generally sounds good to me. It may be better to include the sounds through the main sound pack... i.e. https://github.com/EdgeTX/edgetx-sdcard-sounds ... then these will be available sounding the same as the rest of the phrases for for at minimum the different UK/US EN voice packs?

**Comment by frankiearzu** [comment]
Will do separate SOUNDS..  you are right, that was one think that it did not feel right, since it will not work on multi-language.

**Comment by pfeerick** [comment]
I'll probably have a look at this in the morning or perhaps the day after, but let me know if you are happy with the sound pack phases or want any changes... just needs different text in the `voices/en-US.csv` / `voices/en-GB.csv` files if that is the case.

**Comment by frankiearzu** [comment]
Thank you, i was looking to generate them via Azure.   Will take a look and adapt as needed.

**Comment by ulfhedlund** [comment]
@frankiearzu - If you need someone to test the SoarETX v2 I am happy to help if I can. I have used SoarOTX for both F3K, F3J, F5J and F3RES planes and have one older radio (FrSky QX7) still running OpenTX because of that. I run ETX and can test on Xlite and TX16S.

**Comment by frankiearzu** [comment]
@ulfhedlund Thanks Ulf, I have a Zip with the new code that some friends and myself are using.   Will change some of the sound names in special functions, but everything else will be the same.  The V1 is backward compatible, if you already use a V1 model, it will continue working the same,  

You can download the SoarETX V2 Zip from here:
https://github.com/frankiearzu/DSMTools/tree/main/Planes%20and%20Templates.

**Comment by pfeerick** [comment]
Shall I merge this as it is now, and the changes the sound pack, or is more work needed on this (for this revision at least... it never ends! :rofl: )

**Comment by frankiearzu** [comment]
Testing using some of the standard sounds, and adding some to the common path.
Give me a 1day to test.

**Comment by pfeerick** [comment]
No problem, just checking for a pulse ;)

**Comment by frankiearzu** [comment]
Done!!!
Ended up re-using a few sounds already there, and only added what is missing

The sounds PR is at:
https://github.com/EdgeTX/edgetx-sdcard-sounds/pull/104

**Pull request merged**
