### PR TITLE
Shmuely/gauge rotary v06

### PR DESCRIPTION
**Pull request by offer-shmuely**
widget GaugeRotary: v0.6
better min/max
increase max value (for RPM)
stability changes
log to file (if needed)

### CODE REVIEW

**Comment by pfeerick** [comment]
I see the NV14 version of this at `sdcard/c480x320/WIDGETS/GaugeRotary` is still 0.1... is this a drop-in replacement or are there screen or other specific change needed to update that copy?

**Comment by offer-shmuely** [comment]
Isn't nv14 is the horizontal one?

**Comment by pfeerick** [comment]
No, vertical ;) NV14/EL18 are both vertical.

**Comment by offer-shmuely** [comment]
someone in the past copy all the widgets to the c480x320, assuming it is supported,
but this not the case
we should keep there only the one that is supported

**Comment by pfeerick** [comment]
That was Risto...  So even the c480x320 is problematic (although the only people who will using using that are developers atm since there are no official firmware for that screen resolution)? I would have thought it was mostly fine since the screen was the same width, just taller. It's the portrait/vertical ones that usually don't scale well.

**Comment by offer-shmuely** [comment]
it is depend how the widget was written
the BattCheck for example is very sensitive to sizes
the new value2 is very very generic to different layout (you pay in that it not look perfect on some of the layouts)

anyhow, there is no way to test it on the simulator
I suggest to delete the following, until there will be a demand
BattCheck 
Counter
GaugeRotary

**Pull request merged**
