### PR TITLE
Add more RGB LED lua scripts for MT12

### PR DESCRIPTION
**Pull request by zyren**
I used Github Copilot and, referencing some existing Scripts, wrote some new cool LED light scripts for the MT12, hoping these scripts will be adopted.

### CODE REVIEW

**Comment by 3djc** [comment]
I see some comments in Chinese, could you change those to English?

**Comment by pfeerick** [comment]
These are looking great. You may want to revisit them before I merge this, as https://github.com/EdgeTX/edgetx/pull/4400 has opened it up so that the full 255 range should be properly open for use, rather than capping out at 50 ;)

**Comment by zyren** [comment]
> These are looking great. You may want to revisit them before I merge this, as [EdgeTX/edgetx#4400](https://github.com/EdgeTX/edgetx/pull/4400) has opened it up so that the full 255 range should be properly open for use, rather than capping out at 50 ;)

Oh, EdgeTX/edgetx#4400 solved a major issue. Before this, I always wondered why the brightness changes of each light were so strange. I will retest and modify the Lua script to make it cooler.

**Comment by pfeerick** [comment]
Yeah, I thought you would like that! 🙂  Thanks for the update, these are great!

**Pull request merged**
