### PR TITLE
update timer2 widget to app-mode (full screen mode)

### PR DESCRIPTION
**Pull request by offer-shmuely**

### CODE REVIEW

**Comment by pfeerick** [comment]
I've just tried all the updated widgets, and they are working great AFAICT!. Thank you very much for adding this functionality! :)

Would it be possible to also take into account the 320x480 aspect ratio of the NV14 as part of these changes, or perhaps a future PR if that is preferable? Timer2 is basically ok, so that can just get merged as is unless you think something needs changing. Both BattCheck and Batt_A1 have data "off-screen" though.

**Comment by pfeerick** [comment]
I think the sizing detection is a little off now... This is outputs/old timer2/new timer2

image
image

**Comment by pfeerick** [comment]
That generally looks good on the NV14 regardless of layout or 

image
image

Now it's only the top bar that has gone a bit silly left I think.

**Comment by pfeerick** [comment]
Revisiting this now, sorry for the delay. So the old form of this used to at least show ` -- T# --` in the top bar, and then the time... but the new form omits that as part of the height detection. Do you think you could add that back in (I understand that the name would be too long - just the `T#` or similar annotation) , so that you don't need to remember which timer countdown is for what? 

If you think not, that's fine, and this will be merged as it is.

**Comment by offer-shmuely** [comment]
of course 👍

**Comment by pfeerick** [comment]
Perfect! Thank you :)

**Pull request merged**
