### PR TITLE
Nested GUIs

### PR DESCRIPTION
**Pull request by jfrickmann**
After I labeled my last PR RC1, I got some new ideas and decided to go for it. So this is a completely _new_ RC1...
GUIs can now be nested as editable elements, so one can have subgroups of elements, and a new _custom_ element gives some hooks into the system to make new types of GUI elements.

### CODE REVIEW

**Review by pfeerick — APPROVED** [review]
This will be merged once this is in :  https://github.com/EdgeTX/edgetx/pull/1300

RC1, revision 2? :grin:

**Comment by jfrickmann** [comment]
RC1.1? 🤓

**Comment by pfeerick** [comment]
Sorry, this one slipped my mind entirely. Right to merge?

**Comment by jfrickmann** [comment]
> Sorry, this one slipped my mind entirely. Right to merge?

NP, you have a lot of balls in the air! 
Ready to merge.

**Pull request merged**
