### PR TITLE
BattCheck - 8 cell and li-ion

### PR DESCRIPTION
**Pull request by offer-shmuely**

### CODE REVIEW

**Comment by mha1** [comment]
Hi, I just tested this version. Maybe I am doing it wrong but I can't set/reset the Lithium_Ion options. It is not in the widget options menu list or scrolling further down is not possible.

image

The Lithium_Ion option should be there, right?

`local _options = {
  { "Sensor"     , SOURCE, 0     }, -- default to 'Cels'
  { "Color"      , COLOR , YELLOW},
  { "Shadow"     , BOOL  , 0     },
  { "LowestCell" , BOOL  , 1     }, -- 0=main voltage display shows all-cell-voltage, 1=main voltage display shows lowest-cell
  { "Lithium_Ion"       , BOOL  , 0      }, -- 0=LIPO battery, 1=LI-ION (18650/21500)
}`

**Comment by offer-shmuely** [comment]
the li-ion should be there
I am developing it in 2.7.1 

image



but it look working on 2.8 from the PR
image

**Comment by mha1** [comment]
That is strange. I'll do a clean setup and try again

**Comment by mha1** [comment]
Started from scratch using #76's BattCheck file. All good, must have been doing something wrong. My apologies for the confusion.

image

**Comment by mha1** [comment]
@offer-shmuely Hi Offer, Peter merged the 8 cell radio part into main. I tested BattCheck against the current main for radio and companion ok. It would be great if you could update c320x480 and c470x320 also to handle 8 cells.

**Comment by offer-shmuely** [comment]
How can i test the 480x320, what radio it is in the companion?

**Comment by mha1** [comment]
This is what I found:

c480x320.zip (480x320 pixel landscape orientation color screen radios);
- Flysky PL18
- Flysky Paladin EV (PL18EV)
c320x480.zip (320x480 pixel portrait orientation color screen radios):
- Flysky Nirvana NV14

**Comment by mha1** [comment]
https://github.com/EdgeTX/edgetx/wiki/Flashing-EdgeTX-to-Flysky-PL18-or-Paladin-EV

I think there is no rush for 480x320 as the PL18 support may no be fully implemented.

320x480 NV14 is supported and working. I have it running in companion,

**Comment by pfeerick** [comment]
> I think there is no rush for 480x320 as the PL18 support may no be fully implemented.

It's in development still, i.e. not supported yet. ;)

**Comment by offer-shmuely** [comment]
updated the BattCheck for NV14

- NV14 BattCheck: support li-ion battery
- NV14 BattCheck: support 8 cell 
- NV14 BattCheck: voltage 2 digit precesion
- NV14 BattCheck: fix layout issues

PR: https://github.com/EdgeTX/edgetx-sdcard/pull/80

**Pull request merged**
