### PR TITLE
horus widget: Widget to display the levels of Lipo battery from single analog source

### PR DESCRIPTION
**Pull request by offer-shmuely**
horus widget: Widget to display the levels of lipo battery from single analog source (like the VFAS/A1/A2/mini-quad-flight-controller)

### CODE REVIEW

**Comment by offer-shmuely** [comment]
Please help me to find a better name for that widget, it is a very usfull one,
many people on my club use it by now


This widget display a graphical representation of a Lipo (not other types) battery level, it will automatically detect the cell amount of the battery.
it will take a lipo voltage that received as a single value (as opposed to multi cell values send while using FLVSS liPo Voltage Sensor)
common sources are:

- Transmitter Battery
- FrSky VFAS
- A1/A2 analog voltage
- mini quad flight controller
- radio-master 168
- OMP m2 heli


image


image

**Comment by pfeerick** [comment]
Dammit... I swear I replied to this two days ago! How about something like 'Battery Gauge (Analogs)` or 'Batt Gauge (Analog)' unless that's getting too long (hm, that begs the question what is the maximum length of a widget name... ?)

**Comment by offer-shmuely** [comment]
well, i did not know we allow spaces :-)
I check the length, the mazimum is 13 chars
so we can:

- BattGauge(An)
- Batt Gauge An
- Batt (Analog)

**Comment by pfeerick** [comment]
The last one looks better, the first is more informative 😆

**Comment by offer-shmuely** [comment]
maybe we can find a word that will represent the "total-value"?
since we really get there the full voltage of the total cell (22.2v instead of 3.6v)
any suggestion?

how complicate it to enlarge the widget name? to 20-25 chars?

**Comment by pfeerick** [comment]
It's not something that I can even think of contemplating in the next couple of weeks... just wrong time of the release cycle and year 😆 ... I suspect it won't be too hard, as yaml configuration handling will relax a lot of restrictions around lengths of names as it is no longer restricted to the field sizes that were reserved in the bin files. 

"Batt Total A." 🤔 

then again.... "A. Batt Total' would put it near the top of the list after the buil in widgets if I remember the code for the list creation right 😆 ... although that could do with some TLC as it really should be sorted A-Z.

**Comment by offer-shmuely** [comment]
Well, after more testing, it looks like there is not limitation on the widget name, as it displayed on screen! 
The limit is enforced on the directory name of the widget (edgeTx does not enforce the directory name to be equal to the on-screen name s openTx did)
in addition, the current sort is by the dir name, and not the on-screen-name, strange, but can be change

so we can choose from the following:
1. BattCheck (Analog)
2. BattCheck Analog
3. BattGauge (Analog)
4. BattGauge Analog
5. BattTotal (Analog)
6. BattTotal Analog

I think the best none is the num 1

what do you think?

image

**Comment by pfeerick** [comment]
1 looks good to me also... leaves from for a "digital" source version
should there be such a thing.

 Yeah, we need to sort the list before display... Not sure I've mentioned
that in an issue yet or on discord.

**Pull request merged**
