### PR TITLE
wing wizard & plane wizard & dirs

### LINKED ISSUE #26: Wizards: Delta Wing Wizard
There was a request for a delta wing wizard

### PR DESCRIPTION
**Pull request by offer-shmuely**
edit: this PR started as wing only, but now it contain also enhancement to the plane wizard & directory restructure

Resolves #26 

adding a wizard for wing (per old request)
also added a touch support for next/previous pages
maybe need better pictures (currently used the plane ones)

image

image
image
image
image
image
image

### CODE REVIEW

**Comment by offer-shmuely** [comment]
Need testing, I do not own a wing :-(

**Comment by pfeerick** [comment]
I changed the mixer values as they didn't match Companion when using it's wing wizard - this is what it looks like after the change
image

**Comment by pfeerick** [comment]
Did you want to tweak this one ;) 

image

**Comment by pfeerick** [comment]
btw, on the `runAilConfig` page, you get an overlap between the throttle set on the first page, and the Ail/Ele (unless it's one of the joys of TAER channel order)... I had CH1 for throttle, and CH1/CH2 for AERight/AELeft. Maybe need to somehow think of how to get the defaults channels for A and E also and use them for the elevon channels... companion wizard appears to use ELE for the first elevon channel, and AIL for the second.

**Comment by offer-shmuely** [comment]
I fix the issue you find,
But it looks like another error, i need to search for it.

Please do not merge it to 2.9, i think it needed to be tested on real plane (i do not own a wing myself)

**Comment by pfeerick** [comment]
Might give me an ~excuse~ reason to finally put one of the two I have together. I've not tried the latest version of this out, but when I did before it seemed fine except that the mixes were swapped, which I fixed.

**Comment by pfeerick** [comment]
Hm... got this on the last screen when trying to change from "no" to "yes"

image

**Comment by offer-shmuely** [comment]
Cool,
More work for me 🤪

**Comment by offer-shmuely** [comment]
@pfeerick I have many changes to the file structure, as well as an improved plane wizard
do you like it on this PR (all at once), or after this one?

**Comment by pfeerick** [comment]
You can include it in this PR, will make life a bit easer for both of us ;)

**Comment by offer-shmuely** [comment]
Plane wizard 
- add first widget pages
- add dual rate
- add expo
- add landing gear
- UI improuvments
- allow page-right/left navigation with touch
- fix acknowledge screen after create model

**Comment by offer-shmuely** [comment]
image

image

image

image


image


image

**Comment by offer-shmuely** [comment]
image


image

**Comment by offer-shmuely** [comment]
@pfeerick can that pr be included in 2.9?

**Comment by offer-shmuely** [comment]
> @pfeerick can that pr be included in 2.9?
> 

?

**Comment by pfeerick** [comment]
Ok, finally tried this out. the changes mostly look good. My only concern would be 

1) adding telemetry sensors and setting up LS/SF for them isn't a good idea, as you have zero idea as to what RF system is going to be used, and what sensors it will have available, so it becomes a help or a hinderance. i.e. I just used a flysky receiver, and the transmiter is constantly saying zero volts... as it would if I use frsky without a cell meter, or ELRS, etc, etc. This should be something to be explored in the presets concept. 

2) Need to check through the wing wizard again, as elevator and aileron sticks are swapped - not sure if that was my earlier changes or introduced after that... I thought it was just the surfaces were swapped before in relation to the Companion wizard.

**Comment by offer-shmuely** [comment]
the second one was checked with a real wind of a generous man on the club

**Comment by offer-shmuely** [comment]
For first comment, that is a good question, 
What is better, create new model almost empty from widget and settings, and let the user wondering what and how to add?
Or
Create a new model with couples of widget and settings, and let the user delete what he not needed.
I found that pilot on my club using the old wizard and wondering how to continue...
So i thought it be easier to delete what is not relevant

**Comment by pfeerick** [comment]
There is no easy answer to that. If it is a beginner, then you add the burden on them to find out why it is doing what it is doing and then have to remove it. i.e. how many support requests are we going to get "I just created a plane using the wizard, and now my transmitter keeps telling me 0v?" If it's an intermediate to advanced user, it's fine... but then the question could be why are they using the wizard rather than a template, which has even more stuff set up. My issue is probably more one of the assumption that everyone is using a given RF system that expose that particular telemetry sensor type... which is why I think it is something done better through the presets concept ... "Add a low voltage warning" ... "what RF system are you using (if it can't guess from telemetry)?"... "is this the right sensor?" ... or something like that.

**Pull request merged**
