### PR TITLE
feat(color): model presets

### PR DESCRIPTION
**Pull request by offer-shmuely**

### CODE REVIEW

**Comment by pfeerick** [comment]
Ready to go in now?

**Comment by offer-shmuely** [comment]
I need more feedback...

**Comment by offer-shmuely** [comment]
We can do that.
We need more suggestions to be added, i hope the community will supply some.

did you played with what implemented currently?

**Comment by pfeerick** [comment]
Yes, and it looks really good. 

My only real 2c of input would be that, generally, since you have long enter to confirm for saving settings, I'm not sure you need to long RTN to exit.

For the dual rates... I think you may find some people will want just two rates ... i.e. you might remember hawk from the other day, who does two rates on SF... so it may be worth considering a way to implement that in the future. 

Specifically for the persistent model timer... I think you forgot to make it actually persist? But perhaps the sticking point there was how to trigger it, so it became more an 'adjust' option? Also, it would be nice to be able to choose the timer, as for whatever reason I always use timer 3 as my persistent one. :laughing: :shrug:

**Comment by offer-shmuely** [comment]
Thanks for the good advice :-)

> short RTN would seem to be enough.

done


persistent model timer
> I think you forgot to make it actually persist.

correct, fixed, the line was still commented


> it would be nice to be able to choose the timer

done.


> as for whatever reason I always use timer 3 as my persistent one

I do the same as well


> dual rates...

is there an option to know if the switch is 2 pos, or 3 pos?
if there is, I can do that as well

**Comment by pfeerick** [comment]
Not that I am aware of. It's not going to be "simple" to implement, which is why it's only a thought for later. i.e. sure, you could have a drop down that says how many rates(2/3)... but then for this to work I think you would have to make it so you can pick the switch position for each rate... and also include the not (!) state so you could use a 3POS for 2 rates.  Yes, that is more ... customisable (since you can also choose which rate is toggled where... but we're trying to make things simpler, aren't we?  :rofl: Or maybe that sort of thing is a more advanced dual rates preset?

I'll merge this now, as I want to try and get it some more visibility (i.e. as part of ETX v2.10 - it will get mention in the next RC  announcement as well as final release) and get more feedback and ideas for it.

**Pull request merged**
